name: LCPaxBookingManager-Build

on:
  push:
    branches: [ "main" ]

jobs:

  Step1:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Get-Current-Date
        id: getdate
        run: |
          echo "currentdate=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT      
    outputs:
      DateTime: ${{steps.getdate.outputs.currentdate}}

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-2019
    needs: Step1
    env:
        ReleaseRepoName: Build_Releases_LC
        ReleaseBranchName: LCPaxBookingManager        
        AccountName: ${{ secrets.AccountName }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
        gittoken: ${{ secrets.gittoken }}
        Solution_Name: LCPaxBookingManager.sln
        Project_Name: LCPaxBookingManager.csproj
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Setting up nuget 
      run: |
        dotnet restore


         
    
