name: LCPaxBookingManager-Build

on:
  push:
    branches: [ "main" ]

jobs:

  Step1:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Get-Current-Date
        id: getdate
        run: |
          echo "currentdate=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT      
    outputs:
      DateTime: ${{steps.getdate.outputs.currentdate}}

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-2019
    needs: Step1
    env:
        ReleaseRepoName: Build_Releases_LC
        ReleaseBranchName: LCPaxBookingManager        
        AccountName: ${{ secrets.AccountName }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
        gittoken: ${{ secrets.gittoken }}
        Solution_Name: LCPaxBookingManager.sln
        Project_Name: LCPaxBookingManager.csproj
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Get-Package 
      run: |
        powershell Get-Package -Name *Net*
        
    #- name: Install .Net SDK 4.5.1 
     # run: |
       # powershell Invoke-WebRequest -Uri "https://download.microsoft.com/download/9/6/0/96075294-6820-4F01-924A-474E0023E407/NDP451-KB2861696-x86-x64-DevPack.exe" -OutFile "D:\a\NDP451-KB2861696-x86-x64-DevPack.exe"      
       # powershell Start-Process -Wait -FilePath "D:\a\NDP451-KB2861696-x86-x64-DevPack.exe" -ArgumentList "/Q" -PassThru

    #- name: Get-Package 
     # run: |
       # powershell Get-Package

         
    
